name: DarplexNametags
version: '1.0-SNAPSHOT'
main: com.darplex.darplexNametags.DarplexNametags
api-version: '1.21.1'
depend:
  - packetevents
dependencies:
  server:
    packetevents:
      load: BEFORE
